[project]
name = "timer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydub>=0.25.1",
    "rich>=14.0.0",
    "simpleaudio>=1.0.4",
]
